CREATE TABLE [dbo].[DMD_MARKETER] (

	[MARKETER_KEY] int NULL, 
	[BRANCH_KEY] int NULL, 
	[CLASS_CODE_KEY] int NULL, 
	[QUOTES_TO_MKTG] int NULL, 
	[EMPLOYEE_KEY] int NULL, 
	[CLASS_FGC_CODE_KEY] int NULL, 
	[MARKETER_NAME] varchar(8000) NULL
);