CREATE TABLE [dbo].[DMD_QUOTE_REASON] (

	[QUOTE_REASON_KEY] int NULL, 
	[REASON_DESCRIPTION] varchar(8000) NULL, 
	[REASON_ABBREVIATION] varchar(8000) NULL, 
	[QUOTE_REASON_CATEGORY] varchar(8000) NULL
);