CREATE TABLE [dbo].[DMD_SALESCODE] (

	[SALESCODE_KEY] bigint NULL, 
	[EMPLOYEE_KEY] bigint NULL, 
	[BRANCH_KEY] bigint NULL, 
	[MAIN_CODE] varchar(8000) NULL, 
	[NEWCODE] varchar(8000) NULL, 
	[CMPY] varchar(8000) NULL, 
	[BR] varchar(8000) NULL, 
	[IO] varchar(8000) NULL, 
	[CODE] varchar(8000) NULL, 
	[NAME] varchar(8000) NULL, 
	[NAME_OR] varchar(8000) NULL, 
	[EMPL_NUM] varchar(8000) NULL, 
	[COMM_FLAG] varchar(8000) NULL, 
	[STATUS] varchar(8000) NULL, 
	[TERM_DATE] int NULL, 
	[DEPT_NAME] varchar(8000) NULL, 
	[EMAIL_ADDR] varchar(8000) NULL, 
	[CREA_DATE] int NULL, 
	[MOD_DATE] int NULL, 
	[NAME_LF] varchar(8000) NULL, 
	[ATUSPR_PLAN_TYPE] varchar(8000) NULL, 
	[ATUSPR_SREP_DEPT] varchar(8000) NULL, 
	[COMP] varchar(8000) NULL, 
	[ATUSPR_SREP_SUBX_GRPX] varchar(8000) NULL, 
	[ATUSPR_SREP_STAT] varchar(8000) NULL, 
	[ATUSPR_EMPL_CMPY] varchar(8000) NULL, 
	[ATUSPR_EMPL_DEPT_IDXX] varchar(8000) NULL, 
	[DisplayName] varchar(8000) NULL, 
	[TerminationDate] datetime2(6) NULL, 
	[NT_Account] varchar(8000) NULL, 
	[ASSIGN] varchar(8000) NULL, 
	[SalesDepartment] varchar(8000) NULL
);