CREATE TABLE [dbo].[DMD_DATE_FM] (

	[FISCAL_MONTH_KEY] int NULL, 
	[FISCAL_QUARTER_KEY] int NULL, 
	[FISCAL_YEAR_KEY] int NULL, 
	[FISCAL_MONTH_NUM] int NULL, 
	[FISCAL_MONTH_NAME] varchar(8000) NULL, 
	[FISCAL_MONTH_SEQ] int NULL, 
	[FISCAL_MONTH_DATEFORMAT] datetime2(6) NULL, 
	[FISCAL_IS_FIVE_WEEK] bit NULL, 
	[WEEKS_IN_FISCAL_MONTH] smallint NULL, 
	[FISCAL_LAST_DAY_OF_MONTH] datetime2(6) NULL, 
	[FISCAL_QUARTER_NUM] int NULL, 
	[FISCAL_QUARTER_SEQ] int NULL, 
	[DAYS_IN_FISCAL_MONTH] int NULL, 
	[DAYS_IN_FISCAL_QUARTER] int NULL, 
	[DAYS_IN_FISCAL_YEAR] int NULL
);