CREATE TABLE [dbo].[DMF_QUOTE_FEEDBACK_LINES] (

	[QUOTE_LINE_KEY] int NULL, 
	[FEEDBACK_STATUS_KEY] int NULL, 
	[FOLLOW_UP_DATE] datetime2(6) NULL, 
	[LOST_PRICE] decimal(18,6) NULL, 
	[LOST_TO_COMPETITOR] varchar(8000) NULL, 
	[MOD_STAMP] datetime2(6) NULL, 
	[LOGIN_ID] varchar(8000) NULL, 
	[COMPETITIVE_MFR] varchar(8000) NULL, 
	[COMPETITIVE_PART_NO] varchar(8000) NULL, 
	[CURRENCY_CODE] varchar(8000) NULL, 
	[COMMENTS] varchar(8000) NULL, 
	[LOST_OTHER_COMMENTS] varchar(8000) NULL, 
	[EXPECTED_ORDER_DATE] datetime2(6) NULL, 
	[BUYER] varchar(8000) NULL, 
	[REASON_ID] int NULL, 
	[BUYER_PERSON_ID] varchar(8000) NULL
);