CREATE TABLE [dbo].[DMF_NSB] (

	[NSB_KEY] bigint NULL, 
	[REGION_KEY] bigint NULL, 
	[CMPY_KEY] bigint NULL, 
	[CLASS_CODE_KEY] bigint NULL, 
	[MANUFACTURER_KEY] bigint NULL, 
	[MANUFACTURER_REGION_KEY] bigint NULL, 
	[SHIP_KEY] bigint NULL, 
	[BILLTO_KEY] bigint NULL, 
	[DUNS_KEY] bigint NULL, 
	[DUNSBRMERGED_KEY] bigint NULL, 
	[BRANCH_KEY] bigint NULL, 
	[MERGED_BRANCH_KEY] bigint NULL, 
	[PMCATEGORY_KEY] bigint NULL, 
	[Company] varchar(8000) NULL, 
	[CustomerNo] varchar(8000) NULL, 
	[MFR] varchar(8000) NULL, 
	[Class] varchar(8000) NULL, 
	[CPN] varchar(8000) NULL, 
	[FPN] varchar(8000) NULL, 
	[MPN] varchar(8000) NULL, 
	[InvoiceNo] varchar(8000) NULL, 
	[InvoiceLineNo] decimal(10,0) NULL, 
	[InvoiceDate] datetime2(6) NULL, 
	[Qty] decimal(10,0) NULL, 
	[Sales] decimal(38,8) NULL, 
	[TYPE] varchar(8000) NULL, 
	[OS_ORIG_NEWCODE] varchar(8000) NULL, 
	[IS_ORIG_NEWCODE] varchar(8000) NULL, 
	[OrderDate] datetime2(6) NULL, 
	[WEB_ORDER] int NULL, 
	[ORDER_TYPE] varchar(8000) NULL
);