CREATE TABLE [dbo].[DMF_QUOTE_INTERMEDIATE] (

	[QUOTE_INTERMEDIATE_KEY] int NULL, 
	[QUOTE_KEY] int NULL, 
	[QUOTE_LINE_NO] int NULL, 
	[QUOTE_LINE_KEY] int NULL, 
	[DISTRIBUTION_GROUP] int NULL, 
	[PM_GROUP] int NULL, 
	[LINE_STATUS] varchar(8000) NULL, 
	[DISTRIBUTED_TO] varchar(8000) NULL, 
	[COMPLETED_STAMP] datetime2(6) NULL, 
	[LOGIN_ID] varchar(8000) NULL, 
	[MOD_STAMP] datetime2(6) NULL, 
	[DISTRIBUTED_TO_DATE_STAMP] datetime2(6) NULL, 
	[DISTRIBUTION_TYPE] varchar(8000) NULL, 
	[DISTRIBUTED_TO_ORIGINAL] varchar(8000) NULL
);