CREATE TABLE [dbo].[DMF_QUOTE_MATCHING_AUDIT] (

	[QUOTE_SUBLINE_KEY] int NULL, 
	[QUOTE_SUBLINE_REVISION_KEY] int NULL, 
	[REVISION_NO] int NULL, 
	[MANUFACTURER_NAME] varchar(8000) NULL, 
	[MPN] varchar(8000) NULL, 
	[DESCRIPTION] varchar(8000) NULL, 
	[MATCHED_MPN] varchar(8000) NULL, 
	[MATCHED_Z2_MFR_NAME] varchar(8000) NULL, 
	[MATCHED_FAMILY_ID_KEY] int NULL, 
	[Z2_MATCH_STATUS] varchar(8000) NULL, 
	[REASON] varchar(8000) NULL, 
	[FUTURE_MATCH_STATUS] varchar(8000) NULL, 
	[SCORE] int NULL, 
	[FUTURE_PRODUCT_CLASS] varchar(8000) NULL, 
	[Z2_PRODUCT_CATEGORY] varchar(8000) NULL, 
	[ESTIMATED_VALUE] decimal(18,6) NULL
);