CREATE TABLE [dbo].[SECURITY_DBA_RULES_MKTG] (

	[NT_ACCOUNT] varchar(8000) NULL, 
	[EMAIL] varchar(8000) NULL, 
	[BI_GROUP] varchar(8000) NULL, 
	[PMCATEGORY_KEY] bigint NULL, 
	[RULE_SOURCE] varchar(8000) NULL
);